spring.application.name=API-Gateway
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# =========================================================
# RUTAS DEL GATEWAY
# =========================================================

# Auth Service ? puerto 8080
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://Auth-Service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Audit Service ? puerto 8081
spring.cloud.gateway.server.webflux.routes[1].id=audit-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://Audit-Service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/auditoria/**

# Docs Service ? puerto 8082
spring.cloud.gateway.server.webflux.routes[2].id=docs-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://Docs-Service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/documentos/**

# Vehicle Service ? puerto 8083
spring.cloud.gateway.server.webflux.routes[3].id=vehicle-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://Vehicle-Service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/vehiculos/**

# SAG Service ? puerto 8084
spring.cloud.gateway.server.webflux.routes[4].id=sag-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://SAG-Service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/sag/**

# Report Service ? puerto 8086
spring.cloud.gateway.server.webflux.routes[5].id=report-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://Reporte-Service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/reportes/**

# Logging
logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.example.API.Gateway=DEBUG