server.port=8083
spring.application.name=SAG-Service

# ==========================================
# CONEXIÓN A LA BASE DE DATOS LOCAL
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/secupass_sag?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway desactivado
spring.flyway.enabled=false

# Credenciales para pruebas en Postman
spring.security.user.name=omar_jefe
spring.security.user.password=SecuPass2026!
spring.security.user.roles=USER